---
title: "Bogotá"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
source("R/01-cargar-paquetes.R")
source("R/02-importar-bases-datos.R")

```

```{r, echo=FALSE}
Bogota$cost_day <- round(Bogota$cost_day,1)
names(Bogota) = c("Año-mes", "Grupo-Demo", "Sexo", "Costo diario", "Dieta", "Mes", "Año")


Bogota$`Costo diario` <- as.character(Bogota$`Costo diario`)
Bogota$Año <- as.character(Bogota$Año)
Bogota$Mes <- as.character(Bogota$Mes)
Bogota$Sexo <- as.character(Bogota$Sexo)


datatable(Bogota[, 2:7], 
          filter = 'top', 
          options = list(
            pageLength = 22,         # Cantidad de filas por página
            autoWidth = FALSE,       # Ajusta automáticamente el ancho de las columnas
            dom = 'Brtip',           # Excluye la barra de búsqueda (elimina 'f')
            columnDefs = list(
              list(className = 'dt-center', targets = "_all") # Centrar el contenido
            )
          )
)

```


<br><br>

## Listado de alimentos que requieren imputación 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Lee el archivo de texto
file_path <- "txt-imputacion/output_Bogota.txt"
text_data <- readLines(file_path)

# Extrae nombres de alimentos, excluyendo palabras específicas
library(stringr)

# Define las palabras a excluir
exclude_words <- c("Bogota",
  "and month April", "and month August", "and month December", "and month February", "and month January", 
  "and month July", "and month June", "and month March", "and month May", "and month November", 
  "and month October", "and month September", "April", "August", "December", "February", "January", 
  "July", "June", "kilocalories is", "March", "May", "negra", "November", "October", "September",
  "CoCA", "CoNA", "If you have information for these", "In the city of Medellin for the year ",
  "Iron", " Lipids", "Magnesium", "Niacin", "paquete", "Perejil", "Protein", "Sodium", 
  "the following foods were omitted due to lack of nutritional information", "The nutrients to use in the model are",
  "Thiamine", "to input them", "use the optional parameter called", "VitaminA", "VitaminC", "Zinc","Calcium", "Carbohydrates","cogote","Folate","Lipids",
  "Average daily cost per","caja", "paletero","Phosphorus", "Riboflavin"
)

# Combina las palabras a excluir en un único patrón de expresión regular
exclude_pattern <- paste0("\\b(", paste(exclude_words, collapse = "|"), ")\\b")

# Extrae los posibles nombres de alimentos mediante expresión regular, excluyendo las palabras no deseadas
food_list <- unlist(str_extract_all(text_data, "\\b[A-Za-záéíóúñÑ\\s]+\\b"))

# Filtra las palabras no deseadas de la lista de alimentos
food_list <- food_list[!str_detect(food_list, exclude_pattern)]

# Crea una tabla de frecuencia de los alimentos extraídos
food_frequency <- as.data.frame(table(food_list))

# Renombra columnas para claridad
colnames(food_frequency) <- c("Food", "Frequency")

# Muestra la tabla de frecuencia
print(food_frequency)

```